I, [2017-10-30T20:26:12.954274 #31581]  INFO -- with-pillar-set-ubuntu-1604: -----> Verifying <with-pillar-set-ubuntu-1604>...
I, [2017-10-30T20:26:12.955120 #31581]  INFO -- with-pillar-set-ubuntu-1604: [Shell] Verify on instance=#<Kitchen::Instance:0x000000022f8cb0> with state={:username=>"kitchen", :ssh_key=>"/home/alexfr/Dev/intelics/src/tdagent-formula/.kitchen/docker_id_rsa", :image_id=>"e4e4d64da203", :container_id=>"314852b696b8c44cceae9515c4e8e16e182af9da279f8617e44d1fa49fd8262c", :hostname=>"localhost", :port=>32777, :last_action=>"setup", :last_error=>"Kitchen::ActionFailed"}
E, [2017-10-30T20:26:12.961379 #31581] ERROR -- with-pillar-set-ubuntu-1604: Verify failed on instance <with-pillar-set-ubuntu-1604>.
E, [2017-10-30T20:26:12.961528 #31581] ERROR -- with-pillar-set-ubuntu-1604: ------Exception-------
E, [2017-10-30T20:26:12.961555 #31581] ERROR -- with-pillar-set-ubuntu-1604: Class: Kitchen::ActionFailed
E, [2017-10-30T20:26:12.961572 #31581] ERROR -- with-pillar-set-ubuntu-1604: Message: Action #verify failed for <with-pillar-set-ubuntu-1604>.
E, [2017-10-30T20:26:12.961587 #31581] ERROR -- with-pillar-set-ubuntu-1604: ----------------------
E, [2017-10-30T20:26:12.961599 #31581] ERROR -- with-pillar-set-ubuntu-1604: ------Backtrace-------
E, [2017-10-30T20:26:12.961615 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/verifier/shell.rb:83:in `rescue in shellout'
E, [2017-10-30T20:26:12.961628 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/verifier/shell.rb:80:in `shellout'
E, [2017-10-30T20:26:12.961639 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/verifier/shell.rb:49:in `call'
E, [2017-10-30T20:26:12.961650 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:434:in `block in verify_action'
E, [2017-10-30T20:26:12.961661 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-10-30T20:26:12.961672 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-10-30T20:26:12.961683 #31581] ERROR -- with-pillar-set-ubuntu-1604: /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-10-30T20:26:12.961694 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-10-30T20:26:12.961705 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:426:in `verify_action'
E, [2017-10-30T20:26:12.961719 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-10-30T20:26:12.961730 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-10-30T20:26:12.961741 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-10-30T20:26:12.961751 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-10-30T20:26:12.961761 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-10-30T20:26:12.961772 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-10-30T20:26:12.961782 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-10-30T20:26:12.961793 #31581] ERROR -- with-pillar-set-ubuntu-1604: ----End Backtrace-----
E, [2017-10-30T20:26:12.961803 #31581] ERROR -- with-pillar-set-ubuntu-1604: ---Nested Exception---
E, [2017-10-30T20:26:12.961838 #31581] ERROR -- with-pillar-set-ubuntu-1604: Class: Mixlib::ShellOut::ShellCommandFailed
E, [2017-10-30T20:26:12.961857 #31581] ERROR -- with-pillar-set-ubuntu-1604: Message: Expected process to exit with [0], but received '127'
---- Begin output of testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE ----
STDOUT: 
STDERR: sh: 1: testinfra: not found
---- End output of testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE ----
Ran testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE returned 127
E, [2017-10-30T20:26:12.961873 #31581] ERROR -- with-pillar-set-ubuntu-1604: ----------------------
E, [2017-10-30T20:26:12.961889 #31581] ERROR -- with-pillar-set-ubuntu-1604: ------Backtrace-------
E, [2017-10-30T20:26:12.961918 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/verifier/shell.rb:83:in `rescue in shellout'
E, [2017-10-30T20:26:12.961935 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/verifier/shell.rb:80:in `shellout'
E, [2017-10-30T20:26:12.962218 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/verifier/shell.rb:49:in `call'
E, [2017-10-30T20:26:12.962247 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:434:in `block in verify_action'
E, [2017-10-30T20:26:12.962267 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-10-30T20:26:12.962294 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-10-30T20:26:12.962318 #31581] ERROR -- with-pillar-set-ubuntu-1604: /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-10-30T20:26:12.962347 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-10-30T20:26:12.962368 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:426:in `verify_action'
E, [2017-10-30T20:26:12.962388 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-10-30T20:26:12.962407 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-10-30T20:26:12.962427 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-10-30T20:26:12.962444 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-10-30T20:26:12.962462 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-10-30T20:26:12.962481 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-10-30T20:26:12.962691 #31581] ERROR -- with-pillar-set-ubuntu-1604: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-10-30T20:26:12.962712 #31581] ERROR -- with-pillar-set-ubuntu-1604: ----End Backtrace-----
